// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cardItem': string;
  'cardItemNumber': string;
  'cardSection': string;
  'cardSectionPriority': string;
  'container': string;
  'created': string;
  'dueDate': string;
}
export const cssExports: CssExports;
export default cssExports;
