// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'itemCode': string;
  'itemDottedSplitter': string;
  'itemInfo': string;
  'ms-OverflowSet-item': string;
  'overflowSet': string;
}
export const cssExports: CssExports;
export default cssExports;
