// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'ms-DetailsRow': string;
  'ms-DetailsRow-cell': string;
  'ms-DetailsRow-fields': string;
  'tableTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
