// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'banner': string;
  'container': string;
  'header': string;
  'main': string;
  'table': string;
  'tableColumn': string;
}
export const cssExports: CssExports;
export default cssExports;
